version: '3'
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4070:80'
  api:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_PORT=5432
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_USER=postgres
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
